apiVersion: v1
kind: Pod
metadata:
  name: ambassador-pattern
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
      securityContext:
        privileged: true
    - name: debug
      image: nginx
      # command:
      #   - "curl"
      #   - "localhost:80"
  volumes:
    - name: config-volume
      configMap:
        name: nginx-conf
